travis:
  secure:
    BINSTAR_TOKEN: Pm+eDz1eTkBSrnQt7iZcECxlqQuNIYt/1YuZ+1qTj6P3zgAjQESHhiiBOrVo69869aZNKG2PpWCCBIlvi8we/vauWKIbFJyJgZ7RbpoDR322aBHuMpnzIMog9ThBJkhKGZYNlY5QNa1QZJpKg17GUDxuHzixS/cgoO2YX8vMfhm37JewMyACvhYHHTtDFJIYw0IjIxk4BX2hWGxOc8XXu6KwL2QlL6Fwn0RJgPukh8z9Yh4KD7MUFx/zvTOzmiwt8/OInkwZIWb7R13twxQOLtoiS8BbJ+5Wem4nmigEvd/Z6Ir5YMfcr09Y4qQ5jhoVwq7ZUcovkYZNk25Zx5hSR/NrjskUrhoLmRLEZex4LIlloWv40QLYB0Gc6RaqSan/ei0shgRHPxYYXeba8H2g6HeNBGsEeF1gFq+w5T8HaXdhodX1B/3zD00jPvF3L1DQZahUoTWltVpl5AkYlLu1wYz4A/yBooGas+V8oxcfggkP+1Y0neA0U2eMx9UPF5SKgUXxAtfwJik1vmFfjlMHRbL85/D0cnXTYpauyeiNjWzZM6ZXKGwe/YN2gK9HO+Y91n7RV2cZMPQmevK0ZmgSzIElSg9PYY4/pzrWD54Um1mA7IcNIGLcZEofillgsx2ivvLD47ZMnjfu9AnGfd5GAfOFhMQWdX22go8QraMeudA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
